name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["Feature", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area would this feature affect?
      options:
        - "area: setup"
        - "area: backend"
        - "area: ml"
        - "area: ingestion"
        - "area: image-gen"
        - "area: comic"
        - "area: distribution"
        - "area: ecommerce"
        - "area: release"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - "priority:p0 - Critical (must-have for MVP)"
        - "priority:p1 - High (important for launch)"
        - "priority:p2 - Medium (nice to have)"
        - "priority:p3 - Low (future enhancement)"
      default: 2
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature as a user story
      placeholder: As a [user type], I want [goal] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative approaches
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, wireframes, or examples
      placeholder: Drag images here or provide links
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: Technical notes, dependencies, or concerns
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about this feature
      placeholder: Links, references, or additional details
    validations:
      required: false
