#!/usr/bin/env python3
"""
API Route Generator - Generate Fastify routes + Zod schemas
Usage: python scripts/automation/generators/api-generator.py T25
"""

import sys
import yaml
from pathlib import Path
from typing import Dict, List

WORKSPACE_ROOT = Path('/workspaces/morpheus-press')

def load_task_spec(task_key: str) -> Dict:
    """Load task specification from planning files"""
    effort_map_path = WORKSPACE_ROOT / 'planning/estimates/effort-map.yaml'
    
    with open(effort_map_path, 'r') as f:
        effort_map = yaml.safe_load(f)
    
    if task_key not in effort_map['estimates']:
        raise ValueError(f"Task {task_key} not found")
    
    return effort_map['estimates'][task_key]

def generate_api_route(task_key: str, task_spec: Dict) -> str:
    """Generate Fastify route template"""
    
    route_name = task_spec['title'].lower().replace(' ', '-')
    
    return f"""import {{ FastifyInstance, FastifyRequest, FastifyReply }} from 'fastify';
import {{ z }} from 'zod';

/**
 * Route: {task_spec['title']}
 * Task: {task_key}
 * Generated by automation/generators/api-generator.py
 */

// ============================================
// Request/Response Schemas (Zod)
// ============================================

const CreateItemSchema = z.object({{
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
}});

const UpdateItemSchema = CreateItemSchema.partial();

const ItemResponseSchema = z.object({{
  id: z.string().uuid(),
  name: z.string(),
  description: z.string().nullable(),
  metadata: z.record(z.any()).nullable(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
}});

type CreateItemRequest = z.infer<typeof CreateItemSchema>;
type UpdateItemRequest = z.infer<typeof UpdateItemSchema>;
type ItemResponse = z.infer<typeof ItemResponseSchema>;

// ============================================
// Route Handlers
// ============================================

export async function {route_name.replace('-', '_')}Routes(fastify: FastifyInstance) {{
  // GET /api/items - List all items
  fastify.get<{{
    Querystring: {{ page?: number; limit?: number }};
    Reply: {{ items: ItemResponse[]; total: number }};
  }}>(
    '/api/items',
    {{
      schema: {{
        querystring: {{
          type: 'object',
          properties: {{
            page: {{ type: 'number', minimum: 1, default: 1 }},
            limit: {{ type: 'number', minimum: 1, maximum: 100, default: 20 }},
          }},
        }},
        response: {{
          200: {{
            type: 'object',
            properties: {{
              items: {{ type: 'array' }},
              total: {{ type: 'number' }},
            }},
          }},
        }},
      }},
    }},
    async (request, reply) => {{
      try {{
        const {{ page = 1, limit = 20 }} = request.query;
        
        // TODO: Implement database query
        const items: ItemResponse[] = [];
        const total = 0;
        
        fastify.log.info({{ page, limit, total }}, 'Listed items');
        
        return reply.status(200).send({{ items, total }});
      }} catch (error) {{
        fastify.log.error(error, 'Failed to list items');
        return reply.status(500).send({{
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
        }});
      }}
    }}
  );

  // GET /api/items/:id - Get single item
  fastify.get<{{
    Params: {{ id: string }};
    Reply: ItemResponse;
  }}>(
    '/api/items/:id',
    {{
      schema: {{
        params: {{
          type: 'object',
          properties: {{
            id: {{ type: 'string', format: 'uuid' }},
          }},
          required: ['id'],
        }},
      }},
    }},
    async (request, reply) => {{
      try {{
        const {{ id }} = request.params;
        
        // TODO: Implement database query
        const item: ItemResponse | null = null;
        
        if (!item) {{
          return reply.status(404).send({{
            error: 'Not Found',
            message: `Item ${{id}} not found`,
          }});
        }}
        
        fastify.log.info({{ itemId: id }}, 'Fetched item');
        
        return reply.status(200).send(item);
      }} catch (error) {{
        fastify.log.error(error, 'Failed to fetch item');
        return reply.status(500).send({{
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
        }});
      }}
    }}
  );

  // POST /api/items - Create new item
  fastify.post<{{
    Body: CreateItemRequest;
    Reply: ItemResponse;
  }}>(
    '/api/items',
    {{
      schema: {{
        body: CreateItemSchema,
      }},
    }},
    async (request, reply) => {{
      try {{
        const body = CreateItemSchema.parse(request.body);
        
        // TODO: Implement database insert
        const newItem: ItemResponse = {{
          id: crypto.randomUUID(),
          name: body.name,
          description: body.description ?? null,
          metadata: body.metadata ?? null,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        }};
        
        fastify.log.info({{ itemId: newItem.id }}, 'Created item');
        
        return reply.status(201).send(newItem);
      }} catch (error) {{
        if (error instanceof z.ZodError) {{
          return reply.status(400).send({{
            error: 'Validation Error',
            details: error.errors,
          }});
        }}
        
        fastify.log.error(error, 'Failed to create item');
        return reply.status(500).send({{
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
        }});
      }}
    }}
  );

  // PUT /api/items/:id - Update item
  fastify.put<{{
    Params: {{ id: string }};
    Body: UpdateItemRequest;
    Reply: ItemResponse;
  }}>(
    '/api/items/:id',
    {{
      schema: {{
        params: {{
          type: 'object',
          properties: {{
            id: {{ type: 'string', format: 'uuid' }},
          }},
          required: ['id'],
        }},
        body: UpdateItemSchema,
      }},
    }},
    async (request, reply) => {{
      try {{
        const {{ id }} = request.params;
        const body = UpdateItemSchema.parse(request.body);
        
        // TODO: Implement database update
        const updatedItem: ItemResponse | null = null;
        
        if (!updatedItem) {{
          return reply.status(404).send({{
            error: 'Not Found',
            message: `Item ${{id}} not found`,
          }});
        }}
        
        fastify.log.info({{ itemId: id }}, 'Updated item');
        
        return reply.status(200).send(updatedItem);
      }} catch (error) {{
        if (error instanceof z.ZodError) {{
          return reply.status(400).send({{
            error: 'Validation Error',
            details: error.errors,
          }});
        }}
        
        fastify.log.error(error, 'Failed to update item');
        return reply.status(500).send({{
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
        }});
      }}
    }}
  );

  // DELETE /api/items/:id - Delete item
  fastify.delete<{{
    Params: {{ id: string }};
  }}>(
    '/api/items/:id',
    {{
      schema: {{
        params: {{
          type: 'object',
          properties: {{
            id: {{ type: 'string', format: 'uuid' }},
          }},
          required: ['id'],
        }},
      }},
    }},
    async (request, reply) => {{
      try {{
        const {{ id }} = request.params;
        
        // TODO: Implement database delete
        const deleted = false;
        
        if (!deleted) {{
          return reply.status(404).send({{
            error: 'Not Found',
            message: `Item ${{id}} not found`,
          }});
        }}
        
        fastify.log.info({{ itemId: id }}, 'Deleted item');
        
        return reply.status(204).send();
      }} catch (error) {{
        fastify.log.error(error, 'Failed to delete item');
        return reply.status(500).send({{
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
        }});
      }}
    }}
  );
}}
"""

def main():
    if len(sys.argv) < 2:
        print("Usage: python api-generator.py T25")
        sys.exit(1)
    
    task_key = sys.argv[1]
    
    print(f"🚀 API Route Generator for {task_key}")
    print("="*60)
    
    # Load task spec
    task_spec = load_task_spec(task_key)
    print(f"✅ Task: {task_spec['title']}")
    
    # Generate route
    route_code = generate_api_route(task_key, task_spec)
    
    # Write to file
    route_name = task_spec['title'].lower().replace(' ', '-')
    route_file = WORKSPACE_ROOT / f'apps/backend/src/routes/{route_name}.routes.ts'
    
    route_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(route_file, 'w') as f:
        f.write(route_code)
    
    print(f"✅ Generated: {route_file}")
    print(f"\n📝 Next steps:")
    print(f"   1. Review generated route: {route_file}")
    print(f"   2. Implement database queries (TODO comments)")
    print(f"   3. Register route in app.ts")
    print(f"   4. Generate tests: ./setup-tests.sh {task_key} unit")
    print(f"   5. Test endpoints: pnpm dev:backend")

if __name__ == '__main__':
    main()
