#!/bin/bash
# Supabase Database Setup Generator
# Usage: ./setup-supabase.sh [task_key]
# Example: ./setup-supabase.sh T24

set -e

TASK_KEY=${1:-"T24"}
WORKSPACE_ROOT="/workspaces/morpheus"

echo "🗄️  Supabase Setup Generator for $TASK_KEY"
echo "============================================"

# 1. Check if Supabase is running
if ! supabase status &>/dev/null; then
    echo "⚠️  Supabase not running - starting now..."
    supabase start
fi

# 2. Read task spec from planning/docs
DOCS_DIR="$WORKSPACE_ROOT/planning/docs"
TASK_DOC=$(find "$DOCS_DIR" -name "${TASK_KEY}-*.md" | head -1)

if [ -z "$TASK_DOC" ]; then
    echo "❌ Task documentation not found for $TASK_KEY"
    exit 1
fi

echo "✅ Found task doc: $(basename "$TASK_DOC")"

# 3. Generate migration SQL
MIGRATION_NAME=$(date +%Y%m%d%H%M%S)_${TASK_KEY}_setup
MIGRATION_FILE="$WORKSPACE_ROOT/supabase/migrations/${MIGRATION_NAME}.sql"

echo ""
echo "📝 Generating migration: $MIGRATION_NAME"

cat > "$MIGRATION_FILE" << 'EOF'
-- Migration generated by automation/generators/setup-supabase.sh
-- Task: T24 - Supabase Database Setup with RLS
-- Generated at: $(date -Iseconds)

-- ============================================
-- Database Schema Setup
-- ============================================

-- Example: Create tables (customize based on task spec)
CREATE TABLE IF NOT EXISTS public.example_table (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    data JSONB
);

-- ============================================
-- Row Level Security (RLS) Policies
-- ============================================

ALTER TABLE public.example_table ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own data
CREATE POLICY "Users can read own data" ON public.example_table
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own data
CREATE POLICY "Users can insert own data" ON public.example_table
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own data
CREATE POLICY "Users can update own data" ON public.example_table
    FOR UPDATE
    USING (auth.uid() = user_id);

-- ============================================
-- Indexes for Performance
-- ============================================

CREATE INDEX IF NOT EXISTS idx_example_table_user_id ON public.example_table(user_id);
CREATE INDEX IF NOT EXISTS idx_example_table_created_at ON public.example_table(created_at);

-- ============================================
-- Functions & Triggers
-- ============================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.example_table
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================
-- Grants
-- ============================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.example_table TO authenticated;

EOF

echo "✅ Generated migration: $MIGRATION_FILE"

# 4. Apply migration (dev only)
echo ""
echo "🔄 Applying migration to local Supabase..."
supabase db reset

echo ""
echo "✅ Supabase setup complete for $TASK_KEY!"
echo ""
echo "📝 Next steps:"
echo "   1. Review migration: $MIGRATION_FILE"
echo "   2. Customize tables/policies based on task requirements"
echo "   3. Test RLS policies: pnpm test:backend"
echo "   4. Generate TypeScript types: supabase gen types typescript --local"
